/**
 * Created by syw on 2017/6/19.
 */
const GET_DATA = 'GET_DATA';
const ADD_ITEMNUM ='ADD_ITEMNUM';
const REMBER_ANSWER ='REMBER_ANSWER';
const REMBER_TIME ='REMBER_TIME';
const INITIALIZE_DATA ='INITIALIZE_DATA';
const GET_USER_INFORM ='GET_USER_INFORM';

